---
title: "clean_script"
author: "Ryan Mitchell"
date: "4/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=FALSE, warning=FALSE, message=FALSE}
rm(list = ls())
library(dplyr)
library(ggplot2) 
library(purrr)
library(haven)
library(tidyverse)
# install.packages("DescTools")
library(DescTools)
library(magrittr)
library(kableExtra)
require(plotrix)
# install.packages("magick")
# install.packages("webshot")
library("magick")
library("webshot")
webshot::install_phantomjs()

#install.packages("openxlsx") 
library(openxlsx)
#install.packages("readxl")
library(readxl)
#nstall.packages("rapportools")
library(rapportools)
#install.packages("data.table")
library(data.table)

library(patchwork)
library(sandwich)
library(lmtest)

```

```{r read in policy data script, echo=FALSE, message=FALSE, warning=FALSE}
tab_names <- excel_sheets(path = "data/US_Covid_Policy_data.xlsx")

list_all <- lapply(tab_names, 
                   function(x) read_excel(path = "data/US_Covid_Policy_data.xlsx", 
                                                     sheet = x))
#Rename list elements
names(list_all) <- tab_names %>% 
    tolower() %>%
    gsub(pattern = "_", replacement = " ") %>% 
    str_to_title() %>%
    gsub(pattern = " ", replacement = ".") 

#Rename colums in the DF
for (df in 1:length(list_all)){
  name_qc <- names(list_all)[df] 
  #print(name_qc)
  if(name_qc %in% c("Stay.At.Home", "Unemployment.Benefits")){
    names(list_all[[df]]) <- list_all[[df]][1,]
    list_all[[df]] <- list_all[[df]][-1,]
  }
  
  names(list_all[[df]]) <- gsub(" ", "_", names(list_all[[df]]) %>% tolower())
}

# names(list_all$Stay.At.Home) <- list_all$Stay.At.Home[1,]
# list_all$Stay.At.Home <- list_all$Stay.At.Home[-1,]


#Join the separate sheets into one master sheet
policy_df_0 <- list_all$State.Characteristics %>%
  select(state, state_abbreviation, state_fips_code,
         population = population_2018,
         area_sq_mi = square_miles,
         population_density = population_density_per_square_mile) %>% 
  left_join(list_all$State.Of.Emergency %>% 
              select(state, state_of_emergency_declared = state_of_emergency_issued,), 
            by = "state") %>% 
  left_join(list_all$Masks %>% 
              select(state, begin_mask_mandate = public_face_mask_mandate, end_face_mask_mandate),
            by = "state") %>% 
  mutate(begin_mask_mandate = as.Date(begin_mask_mandate, origin = "1899-12-30"),
         end_face_mask_mandate = as.Date(end_face_mask_mandate, origin = "1899-12-30")) %>%  
  mutate(mask_mandate_flag = ifelse(year(begin_mask_mandate) > 2000, 1, 0)) %>% 
  left_join(list_all$Stay.At.Home %>% 
              select(state,
                     begin_stay_at_home = `stay_at_home/shelter_in_place`, 
                     end_stay_at_home = `end_stay_at_home/shelter_in_place`), 
            by = "state") %>% 
  mutate(begin_stay_at_home = as.Date(begin_mask_mandate, origin = "1899-12-30"),
         end_stay_at_home = as.Date(end_face_mask_mandate, origin = "1899-12-30")) %>%  
  mutate(stay_at_home_flag = ifelse(year(begin_stay_at_home) > 2000, 1, 0)) %>%   
  left_join(list_all$Business.Closures %>% 
              select(state, first_business_closures, first_business_reopening), 
            by = "state") %>% 
  left_join(list_all$Travel.Quarantines %>% 
            select(state, quarantine_mandate_for_some_travelers,
                   quarantine_mandate_for_all_travelers,
                   end_travel_quarantine_mandate = quarantine_mandate_ended), 
            by = "state") %>% 
  mutate(quarantine_mandate_for_some_travelers = as.Date(quarantine_mandate_for_some_travelers, origin = "1899-12-30"),
         quarantine_mandate_for_all_travelers = as.Date(quarantine_mandate_for_all_travelers, origin = "1899-12-30")) %>%  
  mutate(begin_travel_quarantine_mandate = ifelse(quarantine_mandate_for_some_travelers >
                                               quarantine_mandate_for_all_travelers,
                                               quarantine_mandate_for_some_travelers,
                                               quarantine_mandate_for_all_travelers),
         begin_travel_quarantine_mandate = as.Date(begin_travel_quarantine_mandate),
         end_travel_quarantine_mandate = as.Date(end_travel_quarantine_mandate, origin = "1899-12-30")) %>% 
  mutate(travel_quarantine_mandate_flag = ifelse(year(begin_travel_quarantine_mandate) > 2000, 1, 0)) %>%   
  select(-quarantine_mandate_for_some_travelers, -quarantine_mandate_for_all_travelers) %>% 
  left_join(list_all$Unemployment.Benefits %>% 
            select(state,
                   begin_increased_unemployment_benefits = extended_benefits_program_activated,
                   end_increased_unemployment_benefits = extended_benefits_program_deactivated,
                   increased_weekly_unemployment_insurance_amt_thru_jul31 =
                     "weekly_ui_maximum_amount_with_extra_stimulus_(through_july_31,_2020)_(dollars)"), 
            by = "state") %>% 
  mutate(begin_increased_unemployment_benefits = 
           as.Date(as.numeric(begin_increased_unemployment_benefits), 
                   origin = "1899-12-30"),
         end_increased_unemployment_benefits = 
           as.Date(as.numeric(end_increased_unemployment_benefits),
                   origin = "1899-12-30"),
         increased_weekly_unemployment_insurance_amt_thru_jul31 =
           as.numeric(increased_weekly_unemployment_insurance_amt_thru_jul31))
  


saveRDS(policy_df_0, file = "pwd/AggregatedPolicyData.rds")
```

```{r load census, county population, mobility, and covid data, echo=FALSE, warning=FALSE, message=FALSE}
#Read in Census Data
acs_with_overlays <- read_csv("data/ACSDP1Y2019.DP05_data_with_overlays_2021-03-18T145421.csv", 
                              skip = 1, 
                              col_names = TRUE)

names(acs_with_overlays) <-  names(acs_with_overlays) %>% 
    tolower() %>%
    str_to_title() %>%
    gsub(pattern = " ", replacement = ".") %>%
    gsub(pattern = "!!", replacement = ".") %>%
    gsub(pattern = "!", replacement = ".")  


US_mobility_data_0 <- read_csv("data/2020_US_Region_Mobility_Report.csv", 
#                              skip = 1, 
                              col_names = TRUE)

names(US_mobility_data_0) <-  names(US_mobility_data_0) %>% 
    tolower() %>%
    str_to_title() %>%
    gsub(pattern = " ", replacement = ".") #%>%
    #gsub(pattern = "!!", replacement = ".") #%>%
    #gsub(pattern = "!", replacement = ".")  


# Get the area data by state
#https://www2.census.gov/library/publications/2001/compendia/ccdb00/tabB1.pdf
#https://www.census.gov/library/publications/2001/compendia/ccdb00.html
US_population_by_area_0 <- read.xlsx("data/LND01_census_area.xlsx", 
#                              skip = 1, 
                              colNames = TRUE) %>% 
  select(Areaname,	Census_fips_code = STCOU, SqMi = LND110190D)

US_mobility_data <- US_mobility_data_0 %>% 
  left_join(US_population_by_area_0, by = "Census_fips_code") %>% 
  select(-Areaname)

# US_mobility_data_1 %>% select(Census_fips_code) %>%  unique() %>% View()

# Get the population data by state
# https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html#par_textimage_70769902
US_population_by_county_0 <- read_csv("data/co-est2019-alldata.csv", 
#                              skip = 1, 
                              col_names = TRUE) %>% #glimpse()
  # select(COUNTY) %>% unique()
  select(STNAME, CTYNAME, POPESTIMATE2019)

names(US_population_by_county_0) <-  names(US_population_by_county_0) %>% 
    tolower() %>%
    str_to_title()

US_population_by_county <- US_population_by_county_0 %>% 
  group_by(Stname) %>% 
  mutate(StatePop = sum(Popestimate2019)/2) %>% #there is also a state level entry
  ungroup() %>% 
  mutate(CountyPopPerc = Popestimate2019/StatePop) %>% 
  arrange(Stname, desc(CountyPopPerc)) 
          
# US_population_by_county %>% 
#    filter(Stname == "New York") %>% View()
   #summarise(PercSum = sum(CountyPopPerc_Reallocated)) 

# Check to see if the county names match the mobility data county names
US_population_by_county$PresentFlag <- 0
US_population_by_county$Sub_region_2 <- NA

for (i in unique(US_mobility_data$Sub_region_2)){
  US_population_by_county <- US_population_by_county %>% 
    mutate(PresentFlag = if_else(Ctyname %like% i, 1, PresentFlag),
           Sub_region_2 = ifelse(Ctyname %like% i, i, Sub_region_2))
}
US_population_by_county$PresentFlag <- replace_na(US_population_by_county$PresentFlag, 0) 
#US_population_by_county %>% count(PresentFlag)

#Join the mobility data, population data, and area data
US_mobility_data2 <- US_mobility_data %>% 
  dplyr::rename(Stname = Sub_region_1) %>%
  left_join(US_population_by_county %>% 
              select(Stname, 
                     Sub_region_2, 
                     CountyPopPerc,
                     CountyPop = Popestimate2019, 
                     StatePop), 
            by = c("Stname","Sub_region_2")) %>% 
  dplyr::rename(Countyname = Sub_region_2) %>%
  filter(Stname != Countyname)

#Check this date has all 50 states
stopifnot(US_mobility_data2 %>% 
  filter(Date == "2020-03-30") %>% 
  select(Stname) %>% unique() %>% nrow() == 50)

#Add pop dens
US_mobility_data2_highpopdens0 <- US_mobility_data2 %>% 
  mutate(county_pop_dens = CountyPop/SqMi)

# US_mobility_data %>% 
#   filter(Date == "2020-03-30") %>%
#   arrange(desc(county_pop_dens)) %>% 
#   View()

ggplot(US_mobility_data2_highpopdens0 %>% 
         filter(Date == "2020-03-30"), 
       aes(log10(county_pop_dens))) +
  geom_histogram(bins = 100)

#User input
pop_dens_filter <- 2000

ggplot(US_mobility_data2_highpopdens0 %>% 
         filter(Date == "2020-03-30", county_pop_dens < pop_dens_filter), 
       aes((county_pop_dens))) +
  geom_histogram(bins = 100)

#Flag for areas greater than the pop_dens_filter people per sqmi cuttoff
US_mobility_data2_highpopdens <- US_mobility_data2_highpopdens0 %>% 
    mutate(high_popdens_county_flag = ifelse(county_pop_dens > pop_dens_filter, 1, 0))


US_mobility_data2_county_perc_reallocated <- US_mobility_data2_highpopdens %>% 
  filter(Date == "2020-03-30") %>%
  select(Stname, Countyname, CountyPopPerc, high_popdens_county_flag, 
         StatePop, CountyPop) %>% 
  group_by(Stname) %>% 
  mutate(TotalStatePopAccountedFor = sum(CountyPopPerc, na.rm = T),
         CountyPopPerc_Reallocated = CountyPopPerc/TotalStatePopAccountedFor, 
         high_popdens_flag = max(high_popdens_county_flag, na.rm = T)) %>% 
  ungroup()


#QC that all reallocated perc weights totals to 100 
stopifnot(US_mobility_data2_county_perc_reallocated %>% 
  group_by(Stname) %>%
  summarise(PercSum = sum(CountyPopPerc_Reallocated)) %>% # View()
  filter(PercSum < 1.01 & PercSum > .99) %>% 
  nrow() == (US_mobility_data2_highpopdens$Stname %>% 
               unique() %>% length())) # Check no high pop states were dropped 

US_mobility_data2_perc_pop_highdens <- US_mobility_data2_county_perc_reallocated %>% 
  filter(high_popdens_county_flag == 1) %>% 
  group_by(Stname) %>% 
  summarise(high_popdens_pop_perc = sum(CountyPop, na.rm = T)/StatePop) %>% 
  ungroup() %>% 
  distinct(.keep_all = T) %>% 
  filter(!is.na(high_popdens_pop_perc))

#Join new percents and high pop density percents
US_mobility_data3 <- US_mobility_data2_highpopdens %>% 
  left_join(US_mobility_data2_county_perc_reallocated, 
            by = c("Stname", "Countyname")) %>% 
  left_join(US_mobility_data2_perc_pop_highdens, 
            by = "Stname")
  
#reset names
US_mobility_data <- US_mobility_data3
rm(US_mobility_data2, US_mobility_data3, US_population_by_county_0, 
   US_mobility_data2_highpopdens, US_mobility_data2_highpopdens0,
   US_population_by_county, US_population_by_area_0, US_mobility_data_0, 
   US_mobility_data2_county_perc_reallocated)


## Pull data from NYT COVID Database and plot summary
NYT_Data <- fread("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
#summary(NYT_Data)

## Convert date strings to dates. 
NYT_Data[,date:=as.Date(date)]
#summary(NYT_Data)

## Calculate cases on a time interval
start.date <- as.Date("2021-01-01")
end.date <- as.Date("2021-02-28")

interval.cases <- NYT_Data %>%
  arrange(state, 
          date == start.date) %>%
  group_by(state) %>%
  mutate(cases_inc = cases - lag(cases),
         deaths_inc = deaths - lag(deaths)) %>%
  ungroup() %>% 
  filter(cases_inc >= 0)

```

```{r join mobility and covid, echo=FALSE, message=FALSE, warning=FALSE}
#join mobility data with covid database

US_mobility_data_agg <- US_mobility_data %>% 
  dplyr::rename("state" = "Stname",
         "date" = "Date") %>%
  group_by(state, date, high_popdens_pop_perc) %>% 
  mutate(Retail_and_recreation_percent_change_from_baseline_weighted = 
           Retail_and_recreation_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Grocery_and_pharmacy_percent_change_from_baseline_weighted = 
           Grocery_and_pharmacy_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Parks_percent_change_from_baseline_weighted = 
           Parks_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Transit_stations_percent_change_from_baseline_weighted =
           Transit_stations_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Workplaces_percent_change_from_baseline_weighted = 
           Workplaces_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Residential_percent_change_from_baseline_weighted = 
           Residential_percent_change_from_baseline * CountyPopPerc_Reallocated) %>% 
  summarize(Retail_and_recreation_percent_change_from_baseline_weighted = 
              sum(Retail_and_recreation_percent_change_from_baseline_weighted, na.rm = T),
            Grocery_and_pharmacy_percent_change_from_baseline_weighted = 
              sum(Grocery_and_pharmacy_percent_change_from_baseline_weighted, na.rm = T),
            Parks_percent_change_from_baseline_weighted = 
              sum(Parks_percent_change_from_baseline_weighted, na.rm = T),
            Transit_stations_percent_change_from_baseline_weighted = 
              sum(Transit_stations_percent_change_from_baseline_weighted, na.rm = T), 
            Workplaces_percent_change_from_baseline_weighted = 
              sum(Workplaces_percent_change_from_baseline_weighted, na.rm = T),
            Residential_percent_change_from_baseline_weighted = 
              sum(Residential_percent_change_from_baseline_weighted, na.rm = T)) %>% 
  ungroup()

US_cases_and_mobility <- US_mobility_data_agg %>% 
  left_join(interval.cases, by = c("state", "date"))

#QC the join
stopifnot(US_cases_and_mobility %>% nrow()
  == US_mobility_data_agg %>% nrow())

#US_cases_and_mobility %>% 
#  filter(is.na(cases_inc),
#         !is.na(state)) %>% 
#  select(state, cases_inc) %>% nrow()
#1000

#US_cases_and_mobility %>% nrow()
#19800

#1000/19800*100
#[1] 5.1% missing inc cases data
```

```{r data wrangling and final df, echo=FALSE, message=FALSE, warning=FALSE}
#For each state, read in the first 90 days of transit change data, beginning at the date the state declared an emergency 
first_90 <- US_cases_and_mobility %>% 
  left_join(policy_df_0, by = c("state")) %>%
  filter(as.Date(date) >= as.Date(state_of_emergency_declared) & 
           as.Date(date) <= as.Date(state_of_emergency_declared) + 89)
  
#Calculate the mean county-population-weigthed value of transit changes for each state in the first 90 days after emergency declaration
mobility_chg <- aggregate(first_90$Transit_stations_percent_change_from_baseline_weighted, by=list(state=first_90$state), FUN=mean) %>%
  dplyr::rename(mean_transit_change = x)

#Calculate the cumulative cases at 90 days post emergency declaration by state  
cases_at_90 <- aggregate(first_90$cases, by=list(state=first_90$state), FUN=max) %>%
  dplyr::rename(cum_cases_at_90d = x)

#Grab the % of population living in high density variable
high_dens <- aggregate(first_90$high_popdens_pop_perc, by=list(state=first_90$state), FUN=mean) %>%
  dplyr::rename(high_popdens_pop_perc = x)

#Replace NaN with 0
high_dens$high_popdens_pop_perc[is.nan(high_dens$high_popdens_pop_perc)]<-0


final_df <- cases_at_90 %>%
  left_join(policy_df_0, by = c("state")) %>%
  left_join(mobility_chg, by = c("state")) %>%
  left_join(high_dens, by = c("state")) %>%
  mutate(cases_per_100k_at_90d = 100000*cum_cases_at_90d/population) %>%
  left_join(acs_with_overlays, by = c("state" = "Geographic.Area.Name"))
```

```{r transit change vs cases per 100k, echo=FALSE, message=FALSE}
ggplot(data = final_df) +
  geom_point(aes(x = mean_transit_change,
                 y = cases_per_100k_at_90d)) +
  geom_smooth(aes(x = mean_transit_change,
                 y = cases_per_100k_at_90d),
            colour = 'red',
            method = "lm", se = FALSE) + 
  geom_smooth(aes(x = mean_transit_change,
                  y = cases_per_100k_at_90d),
            colour = 'blue',
            method = "loess", se = TRUE) 
```

```{r model, echo=FALSE, message=FALSE}
model_1 <- lm(cases_per_100k_at_90d ~ mean_transit_change + population_density, data = final_df)

qplot(model_1$residuals,
               geom = "histogram", bins = 20) +
         labs(title = "Histogram of residuals",
              x = "residual")

qplot(model_1$fitted, model_1$residuals,
            geom = "point") +
         geom_abline(intercept = 0,
                     slope = 0,
                     colour = "red") +
         labs(title = "Plot of residuals vs fitted values",
              x = "fitted value",
              y = "residual")

cat("-------Coef-------\n")
coefficients(model_1)

cat("\n-------Model results-------\n")
summary(model_1)
cat("\n")
```