---
title: 'Lab 2: Part 1'
author: "Jun Qian, Lucas Schroyer, Ryan Mitchell, Oliver Chang"
output: pdf_document
---

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
rm(list = ls())
library(dplyr)
library(ggplot2) 
library(purrr)
library(haven)
library(tidyverse)
# install.packages("DescTools")
library(DescTools)
library(magrittr)
library(kableExtra)
require(plotrix)
# install.packages("magick")
# install.packages("webshot")
library("magick")
library("webshot")
webshot::install_phantomjs()

#install.packages("openxlsx") 
library(openxlsx)
#nstall.packages("rapportools")
library(rapportools)
#install.packages("data.table")
library(data.table)

library(patchwork)
library(sandwich)
library(lmtest)

```

```{r load data, echo=FALSE, warning=TRUE, message=FALSE}
#Read in Census Data
acs_with_overlays <- read_csv("data/ACSDP1Y2019.DP05_data_with_overlays_2021-03-18T145421.csv", 
                              skip = 1, 
                              col_names = TRUE)

names(acs_with_overlays) <-  names(acs_with_overlays) %>% 
    tolower() %>%
    str_to_title() %>%
    gsub(pattern = " ", replacement = ".") %>%
    gsub(pattern = "!!", replacement = ".") %>%
    gsub(pattern = "!", replacement = ".")  

acs_with_overlays %>% head(3)

```

```{r}
US_mobility_data_0 <- read_csv("data/2020_US_Region_Mobility_Report.csv", 
#                              skip = 1, 
                              col_names = TRUE)

names(US_mobility_data_0) <-  names(US_mobility_data_0) %>% 
    tolower() %>%
    str_to_title() %>%
    gsub(pattern = " ", replacement = ".") #%>%
    #gsub(pattern = "!!", replacement = ".") #%>%
    #gsub(pattern = "!", replacement = ".")  

US_mobility_data_0 %>% glimpse

# Get the area data by state
#https://www2.census.gov/library/publications/2001/compendia/ccdb00/tabB1.pdf
#https://www.census.gov/library/publications/2001/compendia/ccdb00.html
US_population_by_area_0 <- read.xlsx("data/LND01_census_area.xlsx", 
#                              skip = 1, 
                              colNames = TRUE) %>% 
  select(Areaname,	Census_fips_code = STCOU, SqMi = LND110190D)

US_mobility_data <- US_mobility_data_0 %>% 
  left_join(US_population_by_area_0, by = "Census_fips_code") %>% 
  select(-Areaname)

# US_mobility_data_1 %>% select(Census_fips_code) %>%  unique() %>% View()

# Get the population data by state
# https://www.census.gov/data/datasets/time-series/demo/popest/2010s-counties-total.html#par_textimage_70769902
US_population_by_county_0 <- read_csv("data/co-est2019-alldata.csv", 
#                              skip = 1, 
                              col_names = TRUE) %>% #glimpse()
  # select(COUNTY) %>% unique()
  select(STNAME, CTYNAME, POPESTIMATE2019)

names(US_population_by_county_0) <-  names(US_population_by_county_0) %>% 
    tolower() %>%
    str_to_title()

US_population_by_county <- US_population_by_county_0 %>% 
  group_by(Stname) %>% 
  mutate(StatePop = sum(Popestimate2019)/2) %>% #there is also a state level entry
  ungroup() %>% 
  mutate(CountyPopPerc = Popestimate2019/StatePop) %>% 
  arrange(Stname, desc(CountyPopPerc)) 
          
# US_population_by_county %>% 
#    filter(Stname == "New York") %>% View()
   #summarise(PercSum = sum(CountyPopPerc_Reallocated)) 

# Check to see if the county names match the mobility data county names
US_population_by_county$PresentFlag <- 0
US_population_by_county$Sub_region_2 <- NA

for (i in unique(US_mobility_data$Sub_region_2)){
  US_population_by_county <- US_population_by_county %>% 
    mutate(PresentFlag = if_else(Ctyname %like% i, 1, PresentFlag),
           Sub_region_2 = ifelse(Ctyname %like% i, i, Sub_region_2))
}
US_population_by_county$PresentFlag <- replace_na(US_population_by_county$PresentFlag, 0) 
US_population_by_county %>% count(PresentFlag)

# 
# US_population_by_county_qc <- US_population_by_county %>% 
#   count(Stname, PresentFlag) %>% 
#   group_by(Stname) %>% 
#   mutate(n_perc = n/sum(n)) %>% 
#   ungroup()
# 
# US_population_by_county_qc %>% 
#   filter(PresentFlag == 0 | is.na(PresentFlag )
#          & n_perc > .15)
# 
# US_population_by_county_qc %>% 
#   group_by(Stname) %>% 
#   summarise(n_perc_sum = sum(n_perc)) %>% 
#   filter(n_perc_sum < 1)
# 
# #US_population_by_county %>% View()
# 
# x <- US_mobility_data %>% 
#   filter(Sub_region_1 == "Alaska" & !is.na(Sub_region_2)) %>% 
#   select(Sub_region_2) %>% 
#   unique() 
# y <- US_population_by_county %>% 
#     filter(Stname == "Alaska") %>% 
#     select(Ctyname) %>% 
#     unique() 
# x
# y

#Join the mobility data, population data, and area data
US_mobility_data2 <- US_mobility_data %>% 
  dplyr::rename(Stname = Sub_region_1) %>%
  left_join(US_population_by_county %>% 
              select(Stname, 
                     Sub_region_2, 
                     CountyPopPerc,
                     CountyPop = Popestimate2019, 
                     StatePop), 
            by = c("Stname","Sub_region_2")) %>% 
  dplyr::rename(Countyname = Sub_region_2) %>%
  filter(Stname != Countyname)

#Check this date has all 50 states
stopifnot(US_mobility_data2 %>% 
  filter(Date == "2020-03-30") %>% 
  select(Stname) %>% unique() %>% nrow() == 50)

#Add pop dens
US_mobility_data2_highpopdens0 <- US_mobility_data2 %>% 
  mutate(county_pop_dens = CountyPop/SqMi)

# US_mobility_data %>% 
#   filter(Date == "2020-03-30") %>%
#   arrange(desc(county_pop_dens)) %>% 
#   View()

ggplot(US_mobility_data2_highpopdens0 %>% 
         filter(Date == "2020-03-30"), 
       aes(log10(county_pop_dens))) +
  geom_histogram(bins = 100)

#User input
pop_dens_filter <- 2000

ggplot(US_mobility_data2_highpopdens0 %>% 
         filter(Date == "2020-03-30", county_pop_dens < pop_dens_filter), 
       aes((county_pop_dens))) +
  geom_histogram(bins = 100)

#Flag for areas greater than the pop_dens_filter people per sqmi cuttoff
US_mobility_data2_highpopdens <- US_mobility_data2_highpopdens0 %>% 
    mutate(high_popdens_county_flag = ifelse(county_pop_dens > pop_dens_filter, 1, 0))


US_mobility_data2_county_perc_reallocated <- US_mobility_data2_highpopdens %>% 
  filter(Date == "2020-03-30") %>%
  select(Stname, Countyname, CountyPopPerc, high_popdens_county_flag, 
         StatePop, CountyPop) %>% 
  group_by(Stname) %>% 
  mutate(TotalStatePopAccountedFor = sum(CountyPopPerc, na.rm = T),
         CountyPopPerc_Reallocated = CountyPopPerc/TotalStatePopAccountedFor, 
         high_popdens_flag = max(high_popdens_county_flag, na.rm = T)) %>% 
  ungroup()


#QC that all reallocated perc weights totals to 100 
stopifnot(US_mobility_data2_county_perc_reallocated %>% 
  group_by(Stname) %>%
  summarise(PercSum = sum(CountyPopPerc_Reallocated)) %>% # View()
  filter(PercSum < 1.01 & PercSum > .99) %>% 
  nrow() == (US_mobility_data2_highpopdens$Stname %>% 
               unique() %>% length())) # Check no high pop states were dropped 

US_mobility_data2_perc_pop_highdens <- US_mobility_data2_county_perc_reallocated %>% 
  filter(high_popdens_county_flag == 1) %>% 
  group_by(Stname) %>% 
  summarise(high_popdens_pop_perc = sum(CountyPop, na.rm = T)/StatePop) %>% 
  ungroup() %>% 
  distinct(.keep_all = T) %>% 
  filter(!is.na(high_popdens_pop_perc))

#Join new percents and high pop density percents
US_mobility_data3 <- US_mobility_data2_highpopdens %>% 
  left_join(US_mobility_data2_county_perc_reallocated, 
            by = c("Stname", "Countyname")) %>% 
  left_join(US_mobility_data2_perc_pop_highdens, 
            by = "Stname")
  
#reset names
US_mobility_data <- US_mobility_data3
rm(US_mobility_data2, US_mobility_data3, US_population_by_county_0, 
   US_mobility_data2_highpopdens, US_mobility_data2_highpopdens0,
   US_population_by_county, US_population_by_area_0, US_mobility_data_0, 
   US_mobility_data2_county_perc_reallocated)

```



```{r}
## Pull data from NYT COVID Database and plot summary
NYT_Data <- fread("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv")
summary(NYT_Data)

## Convert date strings to dates. 
NYT_Data[,date:=as.Date(date)]
summary(NYT_Data)

## Plot out some case data exploration
#_See the R graph gallery for some beautiful things you can do with ggplot 
#(https://www.r-graph-gallery.com/277-marginal-histogram-for-ggplot2.html))_

state_i <- "New York"
plot_data <- NYT_Data[state == state_i,]
p <- ggplot(plot_data, aes(x=date, y=cases)) + 
  geom_col()
p


```

``` {r}
## Calculate cases on a time interval
start.date <- as.Date("2021-01-01")
end.date <- as.Date("2021-02-28")
state_i <- "New York"
# interval.cases <- NYT_Data[state == state_i & date == end.date, cases] - 
#   NYT_Data[state == state_i & date == start.date, cases]

interval.cases <- NYT_Data %>%
  arrange(state, 
          date == start.date) %>%
  group_by(state) %>%
  mutate(cases_inc = cases - lag(cases),
         deaths_inc = deaths - lag(deaths)) %>%
  ungroup() %>% 
  filter(cases_inc >= 0)

interval.cases %>% glimpse()

#plot_data <- NYT_Data[state == state_i,]
p2 <- ggplot(interval.cases %>% filter(state == state_i),
             aes(x=date, y=cases_inc)) + 
 geom_col()
p2

```


```{r}
#join mobility data with covid database
US_mobility_data$Stname %>% unique()
US_mobility_data %>% glimpse()
interval.cases %>% glimpse

US_mobility_data_agg <- US_mobility_data %>% 
  dplyr::rename("state" = "Stname",
         "date" = "Date") %>%
  group_by(state, date, high_popdens_pop_perc) %>% 
  mutate(Retail_and_recreation_percent_change_from_baseline_weighted = 
           Retail_and_recreation_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Grocery_and_pharmacy_percent_change_from_baseline_weighted = 
           Grocery_and_pharmacy_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Parks_percent_change_from_baseline_weighted = 
           Parks_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Transit_stations_percent_change_from_baseline_weighted =
           Transit_stations_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Workplaces_percent_change_from_baseline_weighted = 
           Workplaces_percent_change_from_baseline * CountyPopPerc_Reallocated,
         Residential_percent_change_from_baseline_weighted = 
           Residential_percent_change_from_baseline * CountyPopPerc_Reallocated) %>% 
  summarize(Retail_and_recreation_percent_change_from_baseline_weighted = 
              sum(Retail_and_recreation_percent_change_from_baseline_weighted, na.rm = T),
            Grocery_and_pharmacy_percent_change_from_baseline_weighted = 
              sum(Grocery_and_pharmacy_percent_change_from_baseline_weighted, na.rm = T),
            Parks_percent_change_from_baseline_weighted = 
              sum(Parks_percent_change_from_baseline_weighted, na.rm = T),
            Transit_stations_percent_change_from_baseline_weighted = 
              sum(Transit_stations_percent_change_from_baseline_weighted, na.rm = T), 
            Workplaces_percent_change_from_baseline_weighted = 
              sum(Workplaces_percent_change_from_baseline_weighted, na.rm = T),
            Residential_percent_change_from_baseline_weighted = 
              sum(Residential_percent_change_from_baseline_weighted, na.rm = T)) %>% 
  ungroup()

US_cases_and_mobility <- US_mobility_data_agg %>% 
  left_join(interval.cases, by = c("state", "date"))

#QC the join
stopifnot(US_cases_and_mobility %>% nrow()
  == US_mobility_data_agg %>% nrow())

US_cases_and_mobility %>% 
  filter(is.na(cases_inc),
         !is.na(state)) %>% 
  select(state, cases_inc) %>% nrow()
#1000

US_cases_and_mobility %>% nrow()
#19800

#1000/19800*100
#[1] 5.1% missing inc cases data


US_cases_and_mobility2 <- US_cases_and_mobility %>% 
  arrange(state, date) %>% 
  group_by(state, high_popdens_pop_perc) %>% 
  mutate(cases_avg_daily_change_2weekpost = (lead(cases, 14) - cases)/14,
         cases_pct_change_2weekpost = (lead(cases, 14) - cases)/
           ((lead(cases, 14) + cases)/2) * 100,
         #get the cum sum
         Retail_and_recreation_percent_change_from_baseline_cum =
           cumsum(Retail_and_recreation_percent_change_from_baseline_weighted), 
         Grocery_and_pharmacy_percent_change_from_baseline_cum =
           cumsum(Grocery_and_pharmacy_percent_change_from_baseline_weighted),
         Parks_percent_change_from_baseline_cum = 
           cumsum(Parks_percent_change_from_baseline_weighted),
         Transit_stations_percent_change_from_baseline_cum = 
           cumsum(Transit_stations_percent_change_from_baseline_weighted), 
         Workplaces_percent_change_from_baseline_cum = 
           cumsum(Workplaces_percent_change_from_baseline_weighted), 
         Residential_percent_change_from_baseline_cum = 
           cumsum(Residential_percent_change_from_baseline_weighted),
         
         #determine avg pre week change
         Retail_and_recreation_percent_change_from_baseline_avg_1weekpre =
          (Retail_and_recreation_percent_change_from_baseline_weighted +
             lag(Retail_and_recreation_percent_change_from_baseline_weighted, 1) +
             lag(Retail_and_recreation_percent_change_from_baseline_weighted, 2) +
             lag(Retail_and_recreation_percent_change_from_baseline_weighted, 3) +
             lag(Retail_and_recreation_percent_change_from_baseline_weighted, 4) +
             lag(Retail_and_recreation_percent_change_from_baseline_weighted, 5) +
             lag(Retail_and_recreation_percent_change_from_baseline_weighted, 6))/7,
         Grocery_and_pharmacy_percent_change_from_baseline_avg_1weekpre = 
          (Grocery_and_pharmacy_percent_change_from_baseline_weighted +
             lag(Grocery_and_pharmacy_percent_change_from_baseline_weighted, 1) +
             lag(Grocery_and_pharmacy_percent_change_from_baseline_weighted, 2) +
             lag(Grocery_and_pharmacy_percent_change_from_baseline_weighted, 3) +
             lag(Grocery_and_pharmacy_percent_change_from_baseline_weighted, 4) +
             lag(Grocery_and_pharmacy_percent_change_from_baseline_weighted, 5) +
             lag(Grocery_and_pharmacy_percent_change_from_baseline_weighted, 6))/7,
         Parks_percent_change_from_baseline_avg_1weekpre =
          (Parks_percent_change_from_baseline_weighted +
             lag(Parks_percent_change_from_baseline_weighted, 1) +
             lag(Parks_percent_change_from_baseline_weighted, 2) +
             lag(Parks_percent_change_from_baseline_weighted, 3) +
             lag(Parks_percent_change_from_baseline_weighted, 4) +
             lag(Parks_percent_change_from_baseline_weighted, 5) +
             lag(Parks_percent_change_from_baseline_weighted, 6))/7,
         Transit_stations_percent_change_from_baseline_avg_1weekpre =
          (Transit_stations_percent_change_from_baseline_weighted +
             lag(Transit_stations_percent_change_from_baseline_weighted, 1) +
             lag(Transit_stations_percent_change_from_baseline_weighted, 2) +
             lag(Transit_stations_percent_change_from_baseline_weighted, 3) +
             lag(Transit_stations_percent_change_from_baseline_weighted, 4) +
             lag(Transit_stations_percent_change_from_baseline_weighted, 5) +
             lag(Transit_stations_percent_change_from_baseline_weighted, 6))/7,
         Workplaces_percent_change_from_baseline_avg_1weekpre =
          (Workplaces_percent_change_from_baseline_weighted +
             lag(Workplaces_percent_change_from_baseline_weighted, 1) +
             lag(Workplaces_percent_change_from_baseline_weighted, 2) +
             lag(Workplaces_percent_change_from_baseline_weighted, 3) +
             lag(Workplaces_percent_change_from_baseline_weighted, 4) +
             lag(Workplaces_percent_change_from_baseline_weighted, 5) +
             lag(Workplaces_percent_change_from_baseline_weighted, 6))/7,
         Residential_percent_change_from_baseline_avg_1weekpre = 
          (Residential_percent_change_from_baseline_weighted +
             lag(Residential_percent_change_from_baseline_weighted, 1) +
             lag(Residential_percent_change_from_baseline_weighted, 2) +
             lag(Residential_percent_change_from_baseline_weighted, 3) +
             lag(Residential_percent_change_from_baseline_weighted, 4) +
             lag(Residential_percent_change_from_baseline_weighted, 5) +
             lag(Residential_percent_change_from_baseline_weighted, 6))/7,
         ) %>%  
  ungroup() 

US_cases_and_mobility2 <- US_cases_and_mobility2 %>% 
  mutate(AvgIndustry_percent_change_from_baseline_avg_1weekpre = 
           rowMeans(US_cases_and_mobility2 %>%  
                      select(
                        Retail_and_recreation_percent_change_from_baseline_avg_1weekpre,
                        Grocery_and_pharmacy_percent_change_from_baseline_avg_1weekpre,
                        Parks_percent_change_from_baseline_avg_1weekpre,
                        Transit_stations_percent_change_from_baseline_avg_1weekpre,
                        Workplaces_percent_change_from_baseline_avg_1weekpre,
                        Residential_percent_change_from_baseline_avg_1weekpre),
             na.rm = T)
  )
  

# US_cases_and_mobility2 %>%
#   select(state, date, cases_pct_change_2weekpost, cases, cases_inc, 
#          sort(current_vars())
#          ) %>%
#   filter(!is.na(cases_pct_change_2weekpost)) %>% 
#   View()
```


```{r}
coeff <- 100

ggplot(data = US_cases_and_mobility2 %>% 
                filter(!is.na(cases_pct_change_2weekpost))) +
  stat_smooth(aes(x = date,
                  y = cases_avg_daily_change_2weekpost/coeff,
                  colour="# Cases Changes (post two-week average)"), 
       show.legend = TRUE,
       method="loess", span=0.1, se=TRUE, alpha=0.3) +
  stat_smooth(aes(x = date,
                  y = cases_pct_change_2weekpost,
                  colour="% Change Cases (post two-week average)"), 
       show.legend = TRUE,
       method="loess", span=0.1, se=TRUE, alpha=0.3) + 
  scale_y_continuous(
    # Features of the first axis
    name = "Change in case counts (100's)",
    # Add a second axis and specify its features
    #sec.axis = sec_axis(~.*coeff, name="percent change (%)")
    sec.axis = sec_axis(~., name="Percent Change (%)")
  ) + 
  #ylab('percent change (%)') + 
  theme_bw() + 
  stat_smooth(aes(x = date, 
                  y = Transit_stations_percent_change_from_baseline_avg_1weekpre,
                  #y = AvgIndustry_percent_change_from_baseline_avg_1weekpre, 
                  colour="Transit Mobility (pre one-week average)"),
              show.legend = TRUE,
              method="loess", span=0.1, se=TRUE, alpha=0.3) + 
  scale_colour_manual(name="Fit", 
                      #values=c("Cases (post two-week average)"="blue", 
                      #         "Mobility (pre one-week average)"="black"))
                      values=c("# Cases Changes (post two-week average)"="blue",
                               "% Change Cases (post two-week average)" = "red",
                               "Transit Mobility (pre one-week average)"="black")) + 
  ggtitle("Change in Covid Cases and Mobility (Transit) for High Density Areas")

ggplot(data = US_cases_and_mobility2 %>% 
# Percent Change         
                filter(!is.na(cases_pct_change_2weekpost))) +
  geom_point(aes(x = Transit_stations_percent_change_from_baseline_avg_1weekpre,
                 y = cases_pct_change_2weekpost)) +
  geom_smooth(aes(x = Transit_stations_percent_change_from_baseline_avg_1weekpre,
                 y = cases_pct_change_2weekpost),
# ABS values
                # filter(!is.na(cases_avg_daily_change_2weekpost))) +
  # geom_point(aes(x = Transit_stations_percent_change_from_baseline_avg_1weekpre,
                 # y = cases_avg_daily_change_2weekpost)) +
  # geom_smooth(aes(x = Transit_stations_percent_change_from_baseline_avg_1weekpre,
                 # y = cases_avg_daily_change_2weekpost),
            
  colour = 'red',
  method = "lm", se = FALSE)

ggplot(data = US_cases_and_mobility2 %>%
# Percent Change         
               filter(!is.na(cases_pct_change_2weekpost))) +
 geom_histogram(aes(x = cases_pct_change_2weekpost))
# ABS values
  #               filter(!is.na(cases_avg_daily_change_2weekpost))) +
  # geom_histogram(aes(x = cases_avg_daily_change_2weekpost))

ggplot(data = US_cases_and_mobility2 %>%
# Percent Change
               filter(!is.na(cases_pct_change_2weekpost))) +
 geom_histogram(aes(x = cases_pct_change_2weekpost))
# ABS Value
  #               filter(!is.na(cases_avg_daily_change_2weekpost))) +
  # geom_histogram(aes(x = Transit_stations_percent_change_from_baseline_avg_1weekpre),
  #                bins = 100)


```



```{r}
#Run regression
model_1 <- lm(cases_pct_change_2weekpost ~
                Transit_stations_percent_change_from_baseline_avg_1weekpre, 
               data = US_cases_and_mobility2 %>% 
                filter(!is.na(cases_pct_change_2weekpost)))

cat("-------Coef-------\n")
coefficients(model_1)

cat("\n-------Model results-------\n")
summary(model_1)
cat("\n")

# calculate the variance-covariance matrix between the betas
cat("-------Var-Cov Matrix-------\n")
varcov <- vcovHC(model_1, type = "HC3")
varcov

cat("\n-------Coef Test-------\n")
coef_test_lm <- coeftest(model_1, varcov)
coef_test_lm

  

```


```{r}

#Model 2. Add a seasonal variable
US_cases_and_mobility3 <- US_cases_and_mobility2 %>% 
  mutate(season = case_when(
    month(date) < 3 | month(date) > 11 ~ "Winter",
    month(date) < 6  ~ "Spring", 
    month(date) < 9 ~ "Summer", 
    month(date) >= 9 ~ "Autumn", 
    TRUE ~ "NA"
  ))

model_2 <- lm(cases_pct_change_2weekpost ~
                Transit_stations_percent_change_from_baseline_avg_1weekpre*season +
                # Transit_stations_percent_change_from_baseline_avg_1weekpre*season +
                high_popdens_pop_perc, 
               data = US_cases_and_mobility3 %>% 
                filter(!is.na(cases_pct_change_2weekpost)))

cat("-------Coef-------\n")
coefficients(model_2)

cat("\n-------Model results-------\n")
summary(model_2)
cat("\n")

# calculate the variance-covariance matrix between the betas
cat("-------Var-Cov Matrix-------\n")
varcov2 <- vcovHC(model_2, type = "HC3")
varcov2

cat("\n-------Coef Test-------\n")
coef_test_lm2 <- coeftest(model_2, varcov2)
coef_test_lm2


```
```{r}
# ggplot(data = US_cases_and_mobility3 %>% 
#                 #filter(!is.na(cases_pct_change_2weekpost))) +
#                 filter(!is.na(cases_avg_daily_change_2weekpost)),
#        aes(x = AvgIndustry_percent_change_from_baseline_avg_1weekpre,
#                  #y = cases_pct_change_2weekpost)) +
#                  y = cases_avg_daily_change_2weekpost,
#                  color = season)) +
#   geom_point() +
#   # geom_smooth(aes(x = AvgIndustry_percent_change_from_baseline_avg_1weekpre,
#   #                #y = cases_pct_change_2weekpost),
#   #                y = cases_avg_daily_change_2weekpost),
#   #           colour = 'red',
#   #           method = "lm", se = FALSE)
#   geom_smooth(method = "nls", formula = y ~ a * x + b, se = F,
#               method.args = list(start = list(a = 0.1, b = 0.1)))

tmp <- US_cases_and_mobility3 %>% 
                #filter(!is.na(cases_pct_change_2weekpost))) +
                filter(!is.na(cases_avg_daily_change_2weekpost))


ggplot(data = tmp,# %>% filter(season == i),
       aes(x = Transit_stations_percent_change_from_baseline_avg_1weekpre,
                 #y = cases_pct_change_2weekpost)) +
                 y = cases_avg_daily_change_2weekpost)) +
  geom_point() +
  geom_smooth(colour = 'red',
            method = "lm", se = FALSE) + 
  facet_grid( ~ season, scales = "free") 



```

