---
title: "Script_1b_readpolicydata"
author: "Lucas Schroyer"
date: "4/4/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, echo=TRUE, warning=FALSE, message=FALSE}
rm(list = ls())
library(dplyr)
library(ggplot2) 
library(purrr)
library(haven)
library(tidyverse)
# install.packages("DescTools")
library(DescTools)
library(magrittr)
library(kableExtra)
require(plotrix)
# install.packages("magick")
# install.packages("webshot")
library("magick")
library("webshot")
webshot::install_phantomjs()

#install.packages("openxlsx") 
library(openxlsx)
#install.packages("readxl")
library(readxl)
#nstall.packages("rapportools")
library(rapportools)
#install.packages("data.table")
library(data.table)

library(patchwork)
library(sandwich)
library(lmtest)

```


# Read in the script
```{r}
tab_names <- excel_sheets(path = "data/US_Covid_Policy_data.xlsx")

list_all <- lapply(tab_names, 
                   function(x) read_excel(path = "data/US_Covid_Policy_data.xlsx", 
                                                     sheet = x))
#Rename list elements
names(list_all) <- tab_names %>% 
    tolower() %>%
    gsub(pattern = "_", replacement = " ") %>% 
    str_to_title() %>%
    gsub(pattern = " ", replacement = ".") 

#Rename colums in the DF
for (df in 1:length(list_all)){
  name_qc <- names(list_all)[df] 
  #print(name_qc)
  if(name_qc %in% c("Stay.At.Home", "Unemployment.Benefits")){
    names(list_all[[df]]) <- list_all[[df]][1,]
    list_all[[df]] <- list_all[[df]][-1,]
  }
  
  names(list_all[[df]]) <- gsub(" ", "_", names(list_all[[df]]) %>% tolower())
}

# names(list_all$Stay.At.Home) <- list_all$Stay.At.Home[1,]
# list_all$Stay.At.Home <- list_all$Stay.At.Home[-1,]


#Join the separate sheets into one master sheet
policy_df_0 <- list_all$State.Characteristics %>%
  select(state, state_abbreviation, state_fips_code,
         population = population_2018,
         area_sq_mi = square_miles,
         population_density = population_density_per_square_mile) %>% 
  left_join(list_all$State.Of.Emergency %>% 
              select(state, state_of_emergency_declared = state_of_emergency_issued,), 
            by = "state") %>% 
  left_join(list_all$Masks %>% 
              select(state, begin_mask_mandate = public_face_mask_mandate, end_face_mask_mandate),
            by = "state") %>% 
  mutate(begin_mask_mandate = as.Date(begin_mask_mandate, origin = "1899-12-30"),
         end_face_mask_mandate = as.Date(end_face_mask_mandate, origin = "1899-12-30")) %>%  
  mutate(mask_mandate_flag = ifelse(year(begin_mask_mandate) > 2000, 1, 0)) %>% 
  left_join(list_all$Stay.At.Home %>% 
              select(state,
                     begin_stay_at_home = `stay_at_home/shelter_in_place`, 
                     end_stay_at_home = `end_stay_at_home/shelter_in_place`), 
            by = "state") %>% 
  mutate(begin_stay_at_home = as.Date(as.numeric(begin_stay_at_home), origin = "1899-12-30"),
         end_stay_at_home = as.Date(as.numeric(end_stay_at_home), origin = "1899-12-30")) %>% 
  mutate(stay_at_home_flag = ifelse(year(begin_stay_at_home) > 2000, 1, 0)) %>%   
  left_join(list_all$Business.Closures %>% 
              select(state, first_business_closures, first_business_reopening), 
            by = "state") %>% 
  left_join(list_all$Travel.Quarantines %>% 
            select(state, quarantine_mandate_for_some_travelers,
                   quarantine_mandate_for_all_travelers,
                   end_travel_quarantine_mandate = quarantine_mandate_ended), 
            by = "state") %>% 
  mutate(quarantine_mandate_for_some_travelers = as.Date(quarantine_mandate_for_some_travelers, origin = "1899-12-30"),
         quarantine_mandate_for_all_travelers = as.Date(quarantine_mandate_for_all_travelers, origin = "1899-12-30")) %>%  
  mutate(begin_travel_quarantine_mandate = ifelse(quarantine_mandate_for_some_travelers >
                                               quarantine_mandate_for_all_travelers,
                                               quarantine_mandate_for_some_travelers,
                                               quarantine_mandate_for_all_travelers),
         begin_travel_quarantine_mandate = as.Date(begin_travel_quarantine_mandate),
         end_travel_quarantine_mandate = as.Date(end_travel_quarantine_mandate, origin = "1899-12-30")) %>% 
  mutate(travel_quarantine_mandate_flag = ifelse(year(begin_travel_quarantine_mandate) > 2000, 1, 0)) %>%   
  select(-quarantine_mandate_for_some_travelers, -quarantine_mandate_for_all_travelers) %>% 
  left_join(list_all$Unemployment.Benefits %>% 
            select(state,
                   begin_increased_unemployment_benefits = extended_benefits_program_activated,
                   end_increased_unemployment_benefits = extended_benefits_program_deactivated,
                   increased_weekly_unemployment_insurance_amt_thru_jul31 =
                     "weekly_ui_maximum_amount_with_extra_stimulus_(through_july_31,_2020)_(dollars)"), 
            by = "state") %>% 
  mutate(begin_increased_unemployment_benefits = 
           as.Date(as.numeric(begin_increased_unemployment_benefits), 
                   origin = "1899-12-30"),
         end_increased_unemployment_benefits = 
           as.Date(as.numeric(end_increased_unemployment_benefits),
                   origin = "1899-12-30"),
         increased_weekly_unemployment_insurance_amt_thru_jul31 =
           as.numeric(increased_weekly_unemployment_insurance_amt_thru_jul31))
  
  
policy_df_0 %>% glimpse()

saveRDS(policy_df_0, file = "pwd/AggregatedPolicyData.rds")

#list_all$Unemployment.Benefits %>% names()
# list_all$State.Of.Emergency %>% head()
```
